KTB-21 Проведена миграция на Kotlinx.Serialization
Untamos25/KotlinTelegramBot pull request #16
Opened 2024-10-26 17:14 UTC by Untamos25

2024-10-27 13:57 UTC, dzenonce requested changes
Не понятно, как выйти из режима обучения, если только не через `/start`. Давай добавим кнопку "В меню".

2024-10-27 13:57 UTC, dzenonce commented on src/main/kotlin/Telegram.kt
> +    val json = Json {
Давай `json` сделаем полем внутри `TelegramBotService()` и не будем передавать через методы. Ведь парсинг `json`-а это по сути задача сервиса, нам не важно в каком виде приходят данные от Telegram API.

2024-10-27 18:10 UTC, Untamos25 commented on src/main/kotlin/Telegram.kt
> +    val json = Json {
Я сначала собирался сразу добавить кнопку "В меню", как и сброс статистики. Но потом увидел, что сброс будем реализовывать далее, и решил отложить эту идею и отправить на проверку ту часть, которая касалась изначальной задачи. Подумал, что лучше сначала узнать, всё ли на данном этапе правильно, потому что тема в этой главе не сразу поддалась пониманию)

2024-10-28 16:03 UTC, dzenonce approved these changes

2024-10-29 10:13 UTC, merged