KTB-07 Реализован вывод вопроса с вариантами ответов из невыученных слов
Untamos25/KotlinTelegramBot pull request #5
Opened 2024-09-24 14:06 UTC by Untamos25

Попытался реализовать вывод вариантов ответа с учётом ТЗ: "из базы выбирается М случайных не выученных слов или максимально возможное количество оставшихся не выученных слов (за неимением таких берутся случайные выученные слова)" + "надо каждый раз показывать следующее неизученное слово". (Это закомментированный вариант). Но не уверен, что иду в правильном направлении. В итоге остановился только за поставленной задаче в блоке KTB-07, где упоминается вывод только неизученных слов.
Посмотри, пожалуйста, правильно ли я рассуждаю и вообще понял поставленную задачу в этом блоке (может быть там имелось в виду реализовать всё то, что я пытался изначально?). И скажи, как я могу доработать код, потому что есть чувство, что оба моих варианта не являются оптимальными. Конечно, там нет ещё проверки введенных значений, чтобы блок выглядел законченным, но сейчас явно уже должно быть видно, смогу ли я на основе имеющегося кода довести эту часть до ума.

2024-09-25 15:17 UTC, kaznikit requested changes

2024-09-25 15:17 UTC, kaznikit commented on src/main/kotlin/Main.kt
> +                    if (dictionary.any { it.correctAnswersCount < NUMBER_OF_CORRECT_REPETITIONS_TO_LEARN_WORD }) {
можем здесь сразу получить список невыученных слов с помощью фильтрации и тогда здесь можно будет просто проверить пустой ли список. не придется 2 раза выбирать невыученные слова)

2024-09-25 15:17 UTC, kaznikit commented on src/main/kotlin/Main.kt
> +                        allWordsToLearn.forEach {
а зачем нам здесь проходиться по всем элементам? нам достаточно достать 1 слово и подобрать для него варианты ответов

2024-09-25 15:17 UTC, kaznikit commented on src/main/kotlin/Main.kt
> +                        allWordsToLearn.forEach {
вообще здесь можно сделать через if. если слов для вариантов ответа у нас достаточно, то мы делаем просто таким образом: 
`unlearnedWords.shuffled().take(4)`

если недостаточно, то нужно добавить слов из выученных. для этого отфильтровать словарь для их получения, затем к списку невыученных добавить недостающее количество выученных

2024-09-25 15:17 UTC, kaznikit commented
> Попытался реализовать вывод вариантов ответа с учётом ТЗ: "из базы выбирается М случайных не выученных слов или максимально возможное количество оставшихся не выученных слов (за неимением таких берутся случайные выученные слова)" + "надо каждый раз показывать следующее неизученное слово". (Это закомментированный вариант). Но не уверен, что иду в правильном направлении. В итоге остановился только за поставленной задаче в блоке KTB-07, где упоминается вывод только неизученных слов. Посмотри, пожалуйста, правильно ли я рассуждаю и вообще понял поставленную задачу в этом блоке (может быть там имелось в виду реализовать всё то, что я пытался изначально?). И скажи, как я могу доработать код, потому что есть чувство, что оба моих варианта не являются оптимальными. Конечно, там нет ещё проверки введенных значений, чтобы блок выглядел законченным, но сейчас явно уже должно быть видно, смогу ли я на основе имеющегося кода довести эту часть до ума.

ответил в комментах, если не получится обсудим еще раз)

2024-09-30 06:34 UTC, danelyan commented
Давай весь код немного порефакторим, чтобы дальше было проще. Записал видео-ревью небольшое:

https://drive.google.com/file/d/1Cc029Bvo9WATCkYfSvuqdFimbftrYEVy/view?usp=drive_link

2024-09-30 06:36 UTC, danelyan requested changes
Давай весь код немного порефакторим, чтобы дальше было проще. Записал видео-ревью небольшое:

https://drive.google.com/file/d/1Cc029Bvo9WATCkYfSvuqdFimbftrYEVy/view?usp=drive_link

2024-09-30 11:30 UTC, Untamos25 commented
> Давай весь код немного порефакторим, чтобы дальше было проще. Записал видео-ревью небольшое:
> 
> https://drive.google.com/file/d/1Cc029Bvo9WATCkYfSvuqdFimbftrYEVy/view?usp=drive_link

Большое спасибо за видео разбор! На этом этапе у меня произошёл дикий затык, хотя сама по себе задача, как и реализация, довольно простые. Плюс ожидание проверки сделали этот блок для меня вообще каким-то бесконечным. Надеюсь, дальше пойдёт лучше, и я завершу этот проект в короткие сроки)

2024-10-01 14:31 UTC, kaznikit approved these changes

2024-10-01 15:18 UTC, merged