KTB-13 Реализован HTTP-запрос с параметром offset
Untamos25/KotlinTelegramBot pull request #9
Opened 2024-10-13 10:55 UTC by Untamos25

2024-10-14 11:40 UTC, dzenonce requested changes
Запрос выполняется верно, но давай немного поправим

2024-10-14 11:40 UTC, dzenonce commented on src/main/kotlin/Telegram.kt
> +        val startUpdateId = updates.lastIndexOf("update_id") + 11
Привет! Давай прибавлять 11 будем после блока `if`, в `substring`, иначе, `startUpdateId` никогда не будет равен -1

2024-10-14 11:40 UTC, dzenonce commented on src/main/kotlin/Telegram.kt
> +        if (startUpdateId == -1 || endUpdateId == -1) continue
Давай еще -1 вынесем в константу избавимся от "магического числа"

2024-10-14 14:36 UTC, Untamos25 commented on src/main/kotlin/Telegram.kt
> +        val startUpdateId = updates.lastIndexOf("update_id") + 11
Привет! Я перенёс +11, но не понимаю, почему именно туда. Разницы в работе кода я не заметил, да и кажется более логичным получить сначала позицию начала Id, а потом уже выполнять проверку... Но, судя по всему, я что-то упускаю и мне нужны твои пояснения)

2024-10-14 18:09 UTC, dzenonce commented on src/main/kotlin/Telegram.kt
> +        val startUpdateId = updates.lastIndexOf("update_id") + 11
```
        val startUpdateId = updates.lastIndexOf("update_id") + 11
        if (startUpdateId == -1 || endUpdateId == -1) continue
```
В таком случае, если startUpdateId и будет равен -1, в блоке if мы этого не узнаем, потому что сразу прибавляем 11 и эта часть всегда будет возвращать false

На данный момент это не критично, но если мы что-то проверяем, то следует следить, работает ли эта проверка вообще

2024-10-14 18:10 UTC, dzenonce approved these changes
Все гуд!

2024-10-15 09:23 UTC, Untamos25 commented on src/main/kotlin/Telegram.kt
> +        val startUpdateId = updates.lastIndexOf("update_id") + 11
А, понял, спасибо! Это настолько очевидно, что даже не знаю, почему в этом моменте у меня вообще возникли вопросы)

2024-10-15 09:24 UTC, merged